<a href="https://colab.research.google.com/github/adityakumarpinjala/BERT-V-s-Word2vec/blob/main/Bert_Vs_word2vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install flair

     |████████████████████████████████| 450kB 5.4MB/s 
     |████████████████████████████████| 1.3MB 8.3MB/s 
     |████████████████████████████████| 1.1MB 13.2MB/s 
     |████████████████████████████████| 19.7MB 72.1MB/s 
     |████████████████████████████████| 798kB 48.5MB/s 
     |████████████████████████████████| 71kB 8.2MB/s 
     |████████████████████████████████| 983kB 40.0MB/s 
     |████████████████████████████████| 2.9MB 45.6MB/s 
     |████████████████████████████████| 890kB 43.9MB/s 
  Created wheel for sqlitedict: filename=sqlitedict-1.7.0-cp36-none-any.whl size=14377 sha256=32f41790a8a6c2c79443036b29a32bc7fd564e8741c360c1d72e701dffe3ffe9
  Stored in directory: /root/.cache/pip/wheels/cf/c6/4f/2c64a43f041415eb8b8740bd80e15e92f0d46c5e464d8e4b9b
  Created wheel for mpld3: filename=mpld3-0.3-cp36-none-any.whl size=116679 sha256=10fdf519f47973f17fb8b98d108b6ff85485ae19e65e0aae41a3aee760ce877d
  Stored in directory: /root/.cache/pip/wheels/c0/47/fb/8a64f89aecfe0059830479308ad42

In [2]:
import numpy as np
from flair.embeddings import WordEmbeddings,TransformerWordEmbeddings
from flair.data import Sentence
from scipy.spatial import distance

**Glove Embeding example**





In [3]:
glove_embedding=WordEmbeddings('glove')

2020-12-16 11:19:11,052 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim.vectors.npy not found in cache, downloading to /tmp/tmpen70p0jm


100%|██████████| 160000128/160000128 [00:13<00:00, 12174695.18B/s]

2020-12-16 11:19:24,560 copying /tmp/tmpen70p0jm to cache at /root/.flair/embeddings/glove.gensim.vectors.npy


2020-12-16 11:19:24,769 removing temp file /tmp/tmpen70p0jm
2020-12-16 11:19:25,651 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim not found in cache, downloading to /tmp/tmpgpau3ieb


100%|██████████| 21494764/21494764 [00:01<00:00, 13879853.41B/s]

2020-12-16 11:19:27,565 copying /tmp/tmpgpau3ieb to cache at /root/.flair/embeddings/glove.gensim
2020-12-16 11:19:27,589 removing temp file /tmp/tmpgpau3ieb


In [9]:
sentence1=Sentence('apple released iphone 12pro max in 2020')

In [11]:
glove_embedding.embed(sentence1)


[Sentence: "apple released iphone 12pro max in 2020"   [− Tokens: 7]]

In [13]:
for token in sentence1:
    print(token)
    print(token.embedding)

Token: 1 apple
tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.0344,

In [15]:
sentence1[0]

Token: 1 apple

In [17]:
sentence1[0].embedding

tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.0344,  1.3431,  0.34

In [19]:

sentence_2 = Sentence('an apple a day keeps the doctor away')

In [20]:
glove_embedding.embed(sentence_2)


[Sentence: "an apple a day keeps the doctor away"   [− Tokens: 8]]

In [21]:
for token in sentence_2:
    print(token)
    print(token.embedding)
    print("\n")

Token: 1 an
tensor([-0.4214, -0.1880,  0.4624, -0.1761,  0.3621,  0.3670,  0.2792,  0.1463,
        -0.0542,  0.4583,  0.0654, -0.3372,  0.0675, -0.3632,  0.5030, -0.0104,
         0.7283, -0.1756, -0.3400,  0.0729,  0.6448, -0.2391,  0.3838,  0.1386,
         1.0994, -0.2488, -0.1508, -0.4874, -0.2304,  0.0648, -0.7018,  0.8265,
         0.0613,  0.1853, -0.3016, -0.0222,  0.3430,  0.8033,  0.1714,  0.1546,
        -0.5076,  0.3957,  0.0543, -0.5308,  0.4825,  0.0862,  0.5958, -0.2238,
        -0.3955, -0.7304, -0.1028, -0.3917,  1.2290,  1.2129, -1.0365, -3.4971,
         0.1092, -1.0084,  1.9998,  0.7964,  0.3881,  0.4375,  0.0852,  0.3855,
         0.6199, -1.0320,  0.7012, -0.2246,  0.0794,  0.0913, -0.2120, -0.5543,
        -0.0534, -0.8020,  0.4680, -0.0501, -0.5742, -0.0848, -1.7227, -0.9429,
         0.9867,  0.3121, -0.3774,  0.0687, -0.7784, -0.2849,  0.8105,  0.4660,
        -0.1186, -0.9341,  0.3372,  0.0379, -0.1827, -0.0199,  0.2049, -0.4772,
        -0.4925, -0.5652,  0

In [22]:
glove_dst = distance.euclidean(np.array(sentence1[0].embedding), 
                               np.array(sentence_2[1].embedding))

In [23]:
print("Distance between apple embeddings for Glove = {}".format(glove_dst))

Distance between apple embeddings for Glove = 0.0


**Bert Embedding**

In [24]:

bert_embedding = TransformerWordEmbeddings('bert-base-multilingual-cased')


In [25]:

bert_embedding.embed(sentence1)
for token in sentence1:
    print(token)
    print(token.embedding)

Token: 1 apple
tensor([-0.5985, -0.4632,  0.1300,  ...,  1.4014, -0.0981,  0.2218])
Token: 2 released
tensor([-0.0451, -0.7260,  0.6271,  ...,  0.8880,  0.3808,  0.4699])
Token: 3 iphone
tensor([-0.3609, -0.5975,  0.5235,  ...,  0.9115, -0.1521, -0.7160])
Token: 4 12pro
tensor([ 0.0000,  0.0000,  0.0000,  ...,  1.1969,  0.2431, -0.4402])
Token: 5 max
tensor([ 0.3356,  0.1247,  0.2099,  ...,  1.3241, -0.3702,  0.7283])
Token: 6 in
tensor([ 0.0857, -0.2220,  0.1657,  ...,  1.4550, -0.2373, -0.1548])
Token: 7 2020
tensor([-0.1241,  0.3447,  0.9852,  ...,  0.8491,  0.9372, -0.2752])


In [26]:
bert_embedding.embed(sentence_2)

for token in sentence_2:
    print(token)
    print(token.embedding)

Token: 1 an
tensor([-0.4214, -0.1880,  0.4624,  ...,  1.2605,  0.8692,  0.1740])
Token: 2 apple
tensor([-0.5985, -0.4632,  0.1300,  ...,  1.8314,  1.0177,  0.2707])
Token: 3 a
tensor([-0.2709,  0.0440, -0.0203,  ...,  0.8354, -0.3497,  0.5959])
Token: 4 day
tensor([-0.3669,  0.4154,  0.1348,  ...,  0.9259, -0.0530,  0.1594])
Token: 5 keeps
tensor([-0.2821,  0.0814,  1.0041,  ...,  0.1253,  0.6754, -0.1647])
Token: 6 the
tensor([-0.0382, -0.2449,  0.7281,  ..., -0.1876, -0.3076,  0.5679])
Token: 7 doctor
tensor([ 0.0432, -0.4753,  0.1581,  ...,  0.7838,  0.3551,  0.3403])
Token: 8 away
tensor([-0.1038, -0.0148,  0.5993,  ...,  1.2423,  0.4363,  0.1388])


In [30]:
bert_dst = distance.euclidean(np.array(sentence1[0].embedding), 
                               np.array(sentence_2[1].embedding))


In [31]:
print("Distance between apple embeddings for Glove = {}".format(bert_dst))

Distance between apple embeddings for Glove = 44.99638748168945
